version: '3.9'

services:
  mywallet-api:
    build: apps/mywallet-api
    container_name: mywallet-api
    restart: unless-stopped
    ports:
      - 5000:80
    networks:
    - mywallet
    
  mywallet-web:
    build: apps/mywallet-web
    container_name: mywallet-web
    restart: unless-stopped
    ports:
      - 5100:80
    networks:
      - mywallet

  postgres:
    image: postgres:15.2-alpine
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - mywallet
    volumes:
      - postgres:/val/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:7.0
    container_name: pg_admin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    networks:
      - mywallet
    volumes:
      - pg_admin:/var/lib/pgadmin

networks:
  mywallet:
    name: mywallet-network

volumes:
  postgres:
    driver: local
  pg_admin:
    driver: local
    